# YAML File for Pose Controller Parameters for PX4-based UAVs in Gazebo Simulation Environment

# This file should keep only the parameters that are additional to pose_px4_params.yaml
# file or have different values than the real drone using the pose_px4_params.yaml file.

geofence: 
  enable: false